# Makefile for $(TOP)/src/csrc

# Copyright 2002 Combex, Inc. under the terms of the MIT X license
# found at http://www.opensource.org/licenses/mit-license.html

default: all

TOP=../..

include $(TOP)/src/build/makerules.mk

DIRS=setup

CLEANDIRS += byaccj
